### ISSUE TITLE
replace JSON ?

### ISSUE THREAD

**Issue by fas3r** [timetocode/tls-json#1]
Hello, 

Would you consider replace JSON by a different parser like [schemapack](https://github.com/phretaddin/schemapack)  or give the possibility to choose the parser that we want to use ?

I'm asking because as the message usually follow as certain pattern/template it could increase the performance

Thanks

**Comment by timetocode** [comment]
There's an advantage to JSON which is that the extra self-describing data allows one to restart the client or server without necessarily having to restart both to change the template. I am open to a PR if it maintains that piece of functionality at least while in JSON mode.  Self-describing binary would maybe be alright, too.

**Comment by fas3r** [comment]
Ok,  I was asking because the repo is archived for jsonstream.
